openapi: 3.0.0
info:
  title: ZahaCRM Bulk API
  description: This is a api for stuff.
  termsOfService: https://example.com/terms/
  contact:
    name: API Support
    url: https://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3.1
servers:
  - url: http://abcdefghi.execute-api.us-east-1.amazonaws.com/api/crm
paths:
  /bulk:
    post:
      summary: Triggers a bulk file create and zip.
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  RESULT:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          default: 3453545345
                      required:
                        - id
      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: false
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: POST
        uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function::PostTriggerBulkFunction/invocations
        responses:
          default:
            statusCode: 200
  /bulk/{fileId}:
    post:
      summary: Returns Completion Status by fileId as ID.
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  RESULT:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          default: 3453545345
                        status:
                          type: string
                          enum:
                            - submitted
                            - processing
                            - completed
                      required:
                        - id
                        - status
      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: false
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: POST
        uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:PostBulkStatusFunction/invocations
        responses:
          default:
            statusCode: 200
  /bulk/{fileId}/read:
    post:
      summary: Returns zipped file object.
      parameters:
        - in: path
          name: fileId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/zip:
              schema:
                type: string
                format: 
      x-amazon-apigateway-request-validators:
        basic:
          validateRequestParameters: false
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: POST
        uri: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:PostBulkDownloadFunction/invocations
        responses:
          default:
            statusCode: 200
