AWSTemplateFormatVersion : "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: ZahaCRM Bulk Rest API Service

Resources:
  ZahaCRMBulkApiGateway: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionUri: ./swagger.yaml
  PostTriggerBulkFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostTriggerBulkFunction
      Runtime: python3.12
      Handler: function.handler
      CodeUri: ./lambda/PostTriggerBulkFunction
      Events:
        PostTriggerBulkApi:
          Type: Api
          Properties:
            RestApiId: !Ref "ZahaCRMBulkApiGateway"
            Path: /api/crm/bulk/
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
  PostBulkStatusFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostBulkStatusFunction
      Runtime: python3.12
      Handler: function.handler
      CodeUri: ./lambda/PostBulkStatusFunction
      Events:
        PostBulkStatusApi:
          Type: Api
          Properties:
            RestApiId: !Ref "ZahaCRMBulkApiGateway"
            Path: /api/crm/bulk/{fileId}
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole
  PostBulkDownloadFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: PostBulkDownloadFunction
      Runtime: python3.12
      Handler: function.handler
      CodeUri: ./lambda/PostBulkDownloadFunction
      Events:
        PostBulkDownloadApi:
          Type: Api
          Properties:
            RestApiId: !Ref "ZahaCRMBulkApiGateway"
            Path: /api/crm/bulk/{fileId}/read
            Method: POST
      Policies:
        - AWSLambdaBasicExecutionRole